version: 2.1

orbs:
  python: circleci/python@0.2.1

dependencies:
    pre:
        - sudo pip install -U platformio

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - compile

compile:
    override:
      - platformio run ${CIRCLE_WORKING_DIRECTORY}/Firmware -e nanoatmega328

workflows:
  main:
    jobs:
      - build
